spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modura
    username: YOUR_USERNAME
    password: YOUR_PASSWORD

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: YOUR_JWT_SECRET

kakao:
  client-id: CLIENT_ID
  redirect-uri: REDIRECT_URI

tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    bearer-token: YOUR_TMDB_BEARER_TOKEN

cloud:
  aws:
    credentials:
      access-key: YOUR_ACCESS_KEY
      secret-key: YOUR_SECRET_KEY