spring:
  application:
    name: modura-server

  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 포맷팅합니다.

  profiles:
    active: dev

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: flicker-bucket